// GENERATED by scripts/gen_plan_format.py -- edit pilot/spec/plan-format.json instead.
// Run that script after changing the contract; `--check` fails the build when this
// file is stale, and launcher/tests/unit/test_spec_format.py asserts the same in CI.

/**
 * Canonical render order for plan-spec sections, shared by the Console
 * (`console/src/`) and the pilot-shell.com SPA (`docs/site/src/`).
 *
 * Both renderers sort recognised `##` headings by this array's index. A heading
 * that is NOT listed here is no longer dropped -- it renders after the recognised
 * ones, in the order it appears in the markdown. That is what lets a plan written
 * by a third-party skill invent its own sections and still display.
 *
 * `SECTIONS_HIDDEN` is the small set that stays invisible, and the two task
 * headings below are rendered by a dedicated task-card component rather than as
 * ordinary sections.
 */
export const DISPLAYED_SECTIONS_ORDERED: readonly string[] = [
  "Summary",
  "Acceptance Criteria",
  "Criteria",
  "Out of Scope",
  "Investigation",
  "Behavior Contract",
  "Approach",
  "Fix Approach",
  "Scope",
  "Autonomous Decisions",
  "Global Constraints",
  "Context for Implementer",
  "Runtime Environment",
  "Feature Inventory",
  "Assumptions",
  "Risks and Mitigations",
  "Goal Verification",
  "E2E Test Scenarios",
  "E2E Results",
  "Verification Scenario",
  "Verification Scenarios",
  "File Structure",
  "Open Questions",
  "Deferred Ideas",
  "Round Log",
  "Changed Files",
] as const;

/**
 * Never rendered as a section on either surface. `Progress Tracking` is already
 * shown by each surface's header card as a task count, so rendering it again
 * would duplicate it.
 */
export const SECTIONS_HIDDEN: readonly string[] = [
  "Progress Tracking",
  "Progress",
] as const;

export const IMPLEMENTATION_TASKS_HEADING = "Implementation Tasks";
export const TASKS_HEADING_BUGFIX = "Tasks";
