#!/usr/bin/env python3
"""Generate the TypeScript section modules from the canonical plan-format contract.

`pilot/spec/plan-format.json` is the single place the section order, hidden
sections and task headings are edited. Neither TypeScript consumer can import it
directly -- both are Vite-rooted (`console/vite.config.ts`,
`docs/site/vite.config.ts`) and a JSON outside the project root is not resolvable
-- so the data is projected into each tree instead.

This replaces a pair of hand-kept byte-identical mirrors. The convention was
"remember to edit both"; the enforcement is `--check` plus the parity test in
`launcher/tests/unit/test_spec_format.py`, which runs in CI where `docs/site`'s
own vitest does not.

Usage:
    python scripts/gen_plan_format.py            # write both files
    python scripts/gen_plan_format.py --check    # exit non-zero if either is stale
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTRACT = REPO_ROOT / "pilot" / "spec" / "plan-format.json"

TARGETS = (
    REPO_ROOT / "console" / "src" / "shared" / "displayed-sections.ts",
    REPO_ROOT / "docs" / "site" / "src" / "lib" / "sharing" / "displayed-sections.ts",
)

_BANNER = "// GENERATED by scripts/gen_plan_format.py -- edit pilot/spec/plan-format.json instead."


def _ts_string_array(values: list[str], indent: str = "  ") -> str:
    return "\n".join(f'{indent}"{value}",' for value in values)


def render(contract: dict) -> str:
    """Render the TypeScript module for `contract`."""
    ordered = contract["sections_ordered"]
    hidden = contract["sections_hidden"]
    tasks_headings = contract["tasks_headings"]

    return f"""{_BANNER}
// Run that script after changing the contract; `--check` fails the build when this
// file is stale, and launcher/tests/unit/test_spec_format.py asserts the same in CI.

/**
 * Canonical render order for plan-spec sections, shared by the Console
 * (`console/src/`) and the pilot-shell.com SPA (`docs/site/src/`).
 *
 * Both renderers sort recognised `##` headings by this array's index. A heading
 * that is NOT listed here is no longer dropped -- it renders after the recognised
 * ones, in the order it appears in the markdown. That is what lets a plan written
 * by a third-party skill invent its own sections and still display.
 *
 * `SECTIONS_HIDDEN` is the small set that stays invisible, and the two task
 * headings below are rendered by a dedicated task-card component rather than as
 * ordinary sections.
 */
export const DISPLAYED_SECTIONS_ORDERED: readonly string[] = [
{_ts_string_array(ordered)}
] as const;

/**
 * Never rendered as a section on either surface. `Progress Tracking` is already
 * shown by each surface's header card as a task count, so rendering it again
 * would duplicate it.
 */
export const SECTIONS_HIDDEN: readonly string[] = [
{_ts_string_array(hidden)}
] as const;

export const IMPLEMENTATION_TASKS_HEADING = "{tasks_headings[0]}";
export const TASKS_HEADING_BUGFIX = "{tasks_headings[1]}";
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit non-zero when a target is stale, printing the diff.",
    )
    args = parser.parse_args()

    try:
        contract = json.loads(CONTRACT.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"error: cannot read {CONTRACT}: {exc}", file=sys.stderr)
        return 2

    expected = render(contract)
    stale: list[Path] = []

    for target in TARGETS:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current == expected:
            continue
        if args.check:
            stale.append(target)
            diff = difflib.unified_diff(
                current.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=f"{target} (committed)",
                tofile=f"{target} (expected)",
            )
            sys.stdout.writelines(diff)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding="utf-8")
            print(f"wrote {target.relative_to(REPO_ROOT)}")

    if args.check and stale:
        names = ", ".join(str(p.relative_to(REPO_ROOT)) for p in stale)
        print(f"\nerror: stale generated file(s): {names}", file=sys.stderr)
        print("Run: python scripts/gen_plan_format.py", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
